const list = [
    {
      id: 1,
      title: "Yellow 2-piece Joggers",
      // author: "by Wonder House Books | 25 April 2018",
      price: 89,
      img: "https://source.unsplash.com/nimElTcTNyY/600x300",
      amount: 1,
      kind: "Bags",
    },
    {
      id: 2,
      title: "Gold Earrings",
      // author: "by Maple Press  | 1 September 2020",
      price: 98,
      img: "https://source.unsplash.com/5ngCICAXiH0/600x300",
      amount: 1,
      kind: "Cloths",
    },
    {
      id: 3,
      title: "White Apple Watch",
      // author: "by Om Books Editorial Team  | 25 November 2018",
      price: 143,
      img: "https://source.unsplash.com/2cFZ_FB08UM/600x300",
      amount: 1,
      kind: "Shoes-Jewelries",
    },
    {
      id: 4,
      title: "Gray Jumpsuit",
      // author: "by Wonder House Books | 25 April 2018",
      price: 57,
      img: "https://source.unsplash.com/0UECcInuCR4/600x300",
      amount: 1,
      kind: "Bags",
    },
    {
      id: 5,
      title: "Necklace, Earring and Ring Set",
      // author: "by Wonder House Books  | 1 January 2018",
      price: 49,
      img: "https://source.unsplash.com/ZcLjr_Y2-z0/600x300",
      amount: 1,
      kind: "Shoes-Jewelries",
    },
    {
      id: 6,
      title: "Nike Sneakers",
      // author: "by Om Books Editorial Team | 30 September 2020",
      price: 135,
      img: "https://source.unsplash.com/jvoZ-Aux9aw/600x300",
      amount: 1,
      kind: "Cloths",
    },
    {
      id: 7,
      title: "SIlver and Pink Rhinestone Heel",
      // author: "by Om Books Editorial Team  | 1 January 2021",
      price: 693,
      img: "https://source.unsplash.com/ndpX28miBtE/600x300",
      amount: 1,
      kind: "Shoes-Jewelries",
    },
    {
      id: 8,
      title: "Peach Handbag",
      // author: "by Wonder House Books  | 6 December 2020",
      price: 289,
      img: "https://source.unsplash.com/N8CwCRjp0LA/600x300",
      amount: 1,
      kind: "CLoths",
    },
    {
      id: 9,
      title: "Cloth",
      // author: "by Content Team at Target Publications",
      price: 80,
      img: "https://source.unsplash.com/sGX-7xDnuE0/600x300",
      amount: 1,
      kind: "Shoes-Jewelries",
    },
    {
      id: 10,
      title: "Black Boot Heel",
      // author: "by Maple Press | 1 September 2021",
      price: 86,
      img: "https://source.unsplash.com/uianIkmhuvk/600x300",
      amount: 1,
      kind: "Bags",
    },
    {
      id: 11,
      title: "Black, Silver Prada Handbag",
      // author: "by Rebecca Smith  | 14 December 2021",
      price: 120,
      img: "https://source.unsplash.com/jC2lLDk55CE/600x300",
      amount: 1,
      kind: "Shoes-Jewelries",
    },
    {
      id: 12,
      title: "Red-roped Heel",
      // author: "by Sudha Murty | 1 January 2015",
      price: 157,
      img: "https://source.unsplash.com/be4eoee4who/600x300",
      amount: 1,
      kind: "Bags",
    },
  ];
  
  export default list;